var config={
    //SOCKET UDP参数配置信息
    socket:{
        server:"",
        port:""
    },
    //iscp安全交互平台参数信息
    iscp:{
        iscpIp:"221.237.156.102:20082",
        serverIp:"221.237.156.102",
        serverPort:"20082",
        serverUser:"user",
        serverAppId:"com.yr.oasgccpublic",
        localIp:"103.46.128.21",
        localPort:"29500"
    },
    //多窗口应用参数信息
    multiWindow:{
        appId:"10000153"
    },
    //企信的生物识别参数信息
    soterAuth:{
        name:"test",
        cardId:"0000000000000"
    },
    //离线人脸识别参数信息
    offline:{
        face:{
            userid:"testh1"
        }
    },
    //沙盒配置信息
    sandbox:{
        userid:"testh1"
    },
    etas:{
        ifaaUrl:"http://192.168.11.121:38080/etas-bizserver/ifaaws/gateway/",
        userID:"userID1",
        transPayload:"测试数据",
        fallbackTitle:"输入密码",
        reasonTitle:"reasonTitle",
        cancelTitle:"cancelTitle"
    },
    //自动测度的时间调用间隔
    timer:{
        wxbase:2000,
        wxext:1000
    }
};

$(function(){
    $("#socketip").val(config.socket.server);
    $("#socketport").val(config.socket.port);

    $("#iscp-iscpip").val(config.iscp.iscpIp);
    $("#iscp-serverip").val(config.iscp.serverIp);
    $("#iscp-serverport").val(config.iscp.serverPort);
    $("#iscp-serveruser").val(config.iscp.serverUser);
    $("#iscp-serverappid").val(config.iscp.serverAppId);
    $("#iscp-localip").val(config.iscp.localIp);
    $("#iscp-localport").val(config.iscp.localPort);

    $("#multiwindowwidget").val(config.multiWindow.appId);
    $("#sandboxreguserid").val(config.sandbox.userid);
    $(".multiwindowwidget").val(config.multiWindow.appId);
    $("#offlinefaceid").val(config.offline.face.userid);
});